name: Build
on:
  push:
    branches: 'master'
jobs:
  build:
    runs-on: [windows-latest]
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      
      - name: Setup MSBuild
        uses: microsoft/setup-msbuild@v1.3.1
        
      - name: Setup NuGet
        uses: NuGet/setup-nuget@v1.2

      - name: Restore NuGet Packages
        run: nuget restore DozeAnywhere.sln

      - name: Download Dalamud
        run: |
          Invoke-WebRequest -Uri https://goatcorp.github.io/dalamud-distrib/stg/latest.zip -OutFile latest.zip
          Expand-Archive -Force latest.zip "$env:AppData\XIVLauncher\addon\Hooks\dev"

      - name: Build
        run: msbuild DozeAnywhere.sln /p:Configuration=Release

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: latest
          path: ./bin/x64/Release
